

DELIMITER //

CREATE PROCEDURE `Prov_Ubi`(IN Ubi CHAR(40))
-- LA IDEA DE ESTE STORE PROCEDURE ES QUE NOS PERMITA FILTRAR A LOS PROVEEDORES POR UBICACION 
BEGIN
	SELECT * FROM Proveedores 
    WHERE dirProv LIKE CONCAT ('%',Ubi,'%');
END//

DELIMITER ;

-- ACA LLAMAMOS A LOS PROVEEDORES QUE ESTAN EN CABA PARA PODER CORROBORAR QUE NUESTRO SP ESTA DANDONOS LA CORRECTA QUERY
call Prov_Ubi ('CABA');

